### ISSUE TITLE
Option to bypass cert validation on HTTPS-enabled Elasticsearch instances

### ISSUE THREAD

**Issue by jibby0** [reportportal/service-auto-analyzer#35]
Hello! We're trying to connect the analyzer to our internal Elasticsearch instance, which is using a self-signed certificate. However, there is currently no way to configure certificate validation regarding the analyzer's Elasticsearch connection.

This results in an error when attempting to connect to an instance using a self-signed cert:

```
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 220, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/venv/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/venv/lib/python3.7/site-packages/urllib3/connection.py", line 371, in connect
    ssl_context=context,
  File "/venv/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/usr/local/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)
```

Perhaps the Elasticsearch option to ignore validation could be exposed, allowing this connection to succeed?

**Comment by MariyaIvanina** [comment]
@jibby0 Hi! I've added several environmental variables for taking care of certification verification and configuration for Elasticsearch. By default, I set for them without certificate verification, but at the Readme file I'll specify all the available environmental variables to use and tune for your needs if verification will be needed in future. This updates will be available from 5.3.1 version.

**Comment by MariyaIvanina** [comment]
@jibby0 Hi! We've released reportportal/service-auto-analyzer:5.3.1 with changes so you can download and check.

**Comment by jibby0** [comment]
Hello! My apologies for the delayed response, I've been on vacation + busy with unassociated work.

Thank you for the quick fix + release! I hope to have it tested in the next few days.

**Comment by jibby0** [comment]
Looks like we're still seeing SSL issues:

```
2020-09-30 19:13:18,352 - analyzerApp.esclient - INFO - Delete logs [5166, 5167] for the project 1
2020-09-30 19:13:18,352 - analyzerApp.esclient - INFO - ES Url https://elasticsearch-controller.logging.svc.cluster.local:9200
2020-09-30 19:14:10,340 - analyzerApp.esclient - ERROR - Index 1 was not found
2020-09-30 19:14:10,342 - analyzerApp.esclient - ERROR - ES Url https://reportportal:<password>@elasticsearch-controller.logging.svc.cluster.local:9200
2020-09-30 19:14:10,342 - analyzerApp.esclient - ERROR - ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076))
```

I played around with the Python shell in the analyzer pod, and it looks like passing `connection_class=elasticsearch.RequestsHttpConnection` will swap the connection class to `requests` instead of `urllib3` (which throws the SSL exception). https://github.com/elastic/elasticsearch-py/issues/712#issuecomment-497251933

The elasticsearch-py docs say this class more resource-intensive though. https://elasticsearch-py.readthedocs.io/en/master/transports.html#transport-classes So there may be a better solution than this.

**Comment by MariyaIvanina** [comment]
@jibby0 Hi! I see, the problem should be resolved by changing this request connection class. I've added the environmental variable ES_TURN_OFF_SSL_VERIFICATION, by default it is "false", and if you set it to "true", then the connection class will be changed to elasticsearch.RequestsHttpConnection. I've released 5.3.2 version with such changes. So try, please, and say whether it helped you.

**Comment by jibby0** [comment]
5.3.2 with `ES_TURN_OFF_SSL_VERIFICATION="true"` is working perfectly with our ES instance! Thanks for resolving this for us!
